"""added a new table for token

Revision ID: 2ddd92797062
Revises: a123c473378c
Create Date: 2023-08-03 11:17:29.974845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ddd92797062'
down_revision = 'a123c473378c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_content', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('expiry_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_content')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    # ### end Alembic commands ###
