"""adjust Blog table

Revision ID: d4e251ef9c39
Revises: eafc79e342b5
Create Date: 2023-08-06 15:38:05.172153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e251ef9c39'
down_revision = 'eafc79e342b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
